export { authService } from './authService'
export { projectService, type ProjectDetail } from './projectService'
export { taskService } from './taskService'
export { contactService } from './contactService'
export { funnelService } from './funnelService'
export { dashboardService } from './dashboardService'
